# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: GI
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:12-alpine
    steps:
      - name: Wait for the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1
        id: netlify
        with:
          site_name: 'dromelpizzadev'
          max_timeout: 120
      - name: execute Ghost Inspector suite
        uses: docker://ghostinspector/cli
        with:
          args: suite execute ${{ secrets.GI_SUITE }} \
            --apiKey ${{ secrets.GI_API_KEY }} \
            --startUrl ${{ secrets.URL }} \
            --errorOnFail
